version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sport-sphere
    ports:
      - "5056:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped